### ISSUE TITLE
trouble with OSD_JOURNAL

### ISSUE THREAD

**Issue by immesys** [ceph/ceph-docker#313]
I'm having some difficulty getting an OSD up. I'm using jewel-ubuntu-16.04. I'm pretty much following the documentation and would really appreciate some help.

I start by preparing the disk, I have the journal on a separate ssd partition. The mon is already up:

```
docker run -it --net=host --privileged=true --pid=host \
   -v /dev/:/dev/ -v /srv/ceph:/var/lib/ceph \
  -e OSD_DEVICE=/dev/sdg -e OSD_JOURNAL=/dev/sda1 \
  -e OSD_FORCE_ZAP=1 -e OSD_TYPE=prepare \
  -e KV_TYPE=etcd -e KV_IP=127.0.0.1 \
  ceph/daemon:tag-build-master-jewel-ubuntu-16.04 osd
```

Which appears to work (full output https://pastee.org/zxz7c)

Then I want to activate it, normally with ceph I'd use the partition (/dev/sdg1), but the documentation suggests the whole disk, so I try that:

```
docker run -it --net=host --privileged=true --pid=host \
  -v /dev/:/dev/  -v /srv/ceph:/var/lib/ceph \
  -e OSD_DEVICE=/dev/sdg -e OSD_JOURNAL=/dev/sda1 \
  -e OSD_TYPE=activate \
  -e KV_TYPE=etcd -e KV_IP=127.0.0.1 \
ceph/daemon:tag-build-master-jewel-ubuntu-16.04 osd
```

But it fails:

```
2016-06-22T02:15:07Z silo confd[4119]: INFO Backend set to etcd
2016-06-22T02:15:07Z silo confd[4119]: INFO Starting confd
2016-06-22T02:15:07Z silo confd[4119]: INFO Backend nodes set to 127.0.0.1:4001
2016-06-22T02:15:07Z silo confd[4119]: INFO Target config /etc/ceph/ceph.conf out of sync
2016-06-22T02:15:07Z silo confd[4119]: INFO Target config /etc/ceph/ceph.conf has been updated
Adding bootstrap keyrings
main_activate: path = /dev/sdg
get_dm_uuid: get_dm_uuid /dev/sdg uuid path is /sys/dev/block/8:96/dm/uuid
command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sdg
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4994, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4945, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3299, in main_activate
    reactivate=args.reactivate,
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3009, in mount_activate
    e,
ceph_disk.main.FilesystemTypeError: Cannot discover filesystem type: device /dev/sdg: Line is truncated:
```

It seems like it dislikes the output of blkid, which is:

```
root@silo:~# blkid /dev/sdg
/dev/sdg: PTUUID="8d9ac31b-59cb-487c-97a0-5d982e62d3cf" PTTYPE="gpt"
```

If I go ahead and try running activate on /dev/sdg1 (with the partition number), I get a different error, where it tries to access the wrong path for the OSD (missing the id):

```
root@silo:~#   docker run -it --net=host --privileged=true --pid=host \
>   -v /dev/:/dev/  -v /srv/ceph:/var/lib/ceph \
>   -e OSD_DEVICE=/dev/sdg1 -e OSD_JOURNAL=/dev/sda1 \
>   -e OSD_TYPE=activate \
>   -e KV_TYPE=etcd -e KV_IP=127.0.0.1 \
> ceph/daemon:tag-build-master-jewel-ubuntu-16.04 osd
2016-06-22T02:18:12Z silo confd[6402]: INFO Backend set to etcd
2016-06-22T02:18:12Z silo confd[6402]: INFO Starting confd
2016-06-22T02:18:12Z silo confd[6402]: INFO Backend nodes set to 127.0.0.1:4001
2016-06-22T02:18:12Z silo confd[6402]: INFO Target config /etc/ceph/ceph.conf out of sync
2016-06-22T02:18:12Z silo confd[6402]: INFO Target config /etc/ceph/ceph.conf has been updated
Adding bootstrap keyrings
main_activate: path = /dev/sdg1
get_dm_uuid: get_dm_uuid /dev/sdg1 uuid path is /sys/dev/block/8:97/dm/uuid
command: Running command: /sbin/blkid -o udev -p /dev/sdg1
command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sdg1
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
mount: Mounting /dev/sdg1 on /var/lib/ceph/tmp/mnt.JZnMvl with options noatime,inode64
command_check_call: Running command: /bin/mount -t xfs -o noatime,inode64 -- /dev/sdg1 /var/lib/ceph/tmp/mnt.JZnMvl
activate: Cluster uuid is 2687e05a-d395-4154-9c3d-1b1917be5e62
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
activate: Cluster name is ceph
activate: OSD uuid is c4b2f616-ce9d-4ea7-b9ed-007f3452395a
allocate_osd_id: Allocating OSD id...
command: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd create --concise c4b2f616-ce9d-4ea7-b9ed-007f3452395a
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.JZnMvl/whoami.6434.tmp
activate: OSD id is 0
activate: Initializing OSD...
command_check_call: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/tmp/mnt.JZnMvl/activate.monmap
got monmap epoch 1
command: Running command: /usr/bin/timeout 300 ceph-osd --cluster ceph --mkfs --mkkey -i 0 --monmap /var/lib/ceph/tmp/mnt.JZnMvl/activate.monmap --osd-data /var/lib/ceph/tmp/mnt.JZnMvl --osd-journal /var/lib/ceph/tmp/mnt.JZnMvl/journal --osd-uuid c4b2f616-ce9d-4ea7-b9ed-007f3452395a --keyring /var/lib/ceph/tmp/mnt.JZnMvl/keyring --setuser ceph --setgroup disk
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup init
command: Running command: /usr/bin/ceph-detect-init --default sysvinit
activate: Marking with init system systemd
activate: Authorizing OSD key...
command_check_call: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring auth add osd.0 -i /var/lib/ceph/tmp/mnt.JZnMvl/keyring osd allow * mon allow profile osd
added key for osd.0
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.JZnMvl/active.6434.tmp
activate: ceph osd.0 data dir is ready at /var/lib/ceph/tmp/mnt.JZnMvl
move_mount: Moving mount to final location...
command_check_call: Running command: /bin/mount -o noatime,inode64 -- /dev/sdg1 /var/lib/ceph/osd/ceph-0
command_check_call: Running command: /bin/umount -l -- /var/lib/ceph/tmp/mnt.JZnMvl
start_daemon: Starting ceph osd.0...
command_check_call: Running command: /bin/systemctl enable ceph-osd@0
Created symlink /etc/systemd/system/ceph-osd.target.wants/ceph-osd@0.service, pointing to /lib/systemd/system/ceph-osd@.service.
command_check_call: Running command: /bin/systemctl start ceph-osd@0
Running in chroot, ignoring request.
df: /var/lib/ceph/osd/ceph-/: No such file or directory
2016-06-22 02:18:27.186965 7f5d0e35a700 -1 auth: unable to find a keyring on /var/lib/ceph/osd/ceph-/keyring: (2) No such file or directory
2016-06-22 02:18:27.186972 7f5d0e35a700 -1 monclient(hunting): ERROR: missing keyring, cannot use cephx for authentication
2016-06-22 02:18:27.186973 7f5d0e35a700  0 librados: osd. initialization error (2) No such file or directory
Error connecting to cluster: ObjectNotFound
```

The underlying volume directory doesn't seem to have any keys for the OSD

```
root@silo:/srv/ceph# find .
./bootstrap-mds
./bootstrap-mds/ceph.keyring
./tmp
./tmp/ceph-disk.activate.lock
./tmp/ceph-disk.prepare.lock
./bootstrap-rgw
./bootstrap-rgw/ceph.keyring
./bootstrap-osd
./bootstrap-osd/ceph.keyring
./ceph
./osd
./osd/ceph-0
./mon
./mon/ceph-silo
./mon/ceph-silo/keyring
./mon/ceph-silo/store.db
./mon/ceph-silo/store.db/000005.ldb
./mon/ceph-silo/store.db/LOCK
./mon/ceph-silo/store.db/CURRENT
./mon/ceph-silo/store.db/MANIFEST-000004
./mon/ceph-silo/store.db/000006.log
```

Again, I would really appreciate any help. I'm about to destroy and recreate everything using the trusty jewel images to see if that helps.

**Comment by immesys** [comment]
Incidentally on the trusty images, both of these also fail, so I must be doing something wrong.

**Comment by immesys** [comment]
Also incidentally, everything works as expected if I do not specify the journal. This only happens once I specify OSD_JOURNAL.

**Comment by immesys** [comment]
Although I am not familiar with the code, I believe #314 would fix this problem. (It does on my side).

**Comment by leseb** [comment]
Thanks for the investigation and the fix :)

**Comment by Raboo** [comment]
I wanted to try this fix, but I'm guessing it's not working because the jewel tag fails to build in docker hub?
https://hub.docker.com/r/ceph/daemon/builds/bybfburnh92az44kffaafjk/
