### ISSUE TITLE
ceph_disk.main.FilesystemTypeError: Cannot discover filesystem type

### ISSUE THREAD

**Issue by Raboo** [ceph/ceph-docker#324]
I'm running ceph/daemon:tag-build-master-jewel-ubuntu-14.04 osd with following environment variables:
```
-e OSD_DEVICE=/dev/sda \
-e OSD_JOURNAL=/dev/nvme0n1p1 \
-e KV_TYPE=consul \
-e KV_IP=192.168.0.1 \
-e KV_PORT=8500
```
and I get following error `ceph_disk.main.FilesystemTypeError: Cannot discover filesystem type: device /dev/sda: Line is truncated:`

#### docker logs -f ceph-osd-sda
```
2016-07-06T09:07:25Z vm04 confd[7674]: INFO Backend set to consul
2016-07-06T09:07:25Z vm04 confd[7674]: INFO Starting confd
2016-07-06T09:07:25Z vm04 confd[7674]: INFO Backend nodes set to vm01.se-ix.delta.prod:8500
2016-07-06T09:07:25Z vm04 confd[7674]: INFO Target config /etc/ceph/ceph.conf out of sync
2016-07-06T09:07:25Z vm04 confd[7674]: INFO Target config /etc/ceph/ceph.conf has been updated
Adding bootstrap keyrings
No bootstrapped OSDs found; trying ceph-disk
HEALTH_OK
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
command: Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=osd_journal_size
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
get_dm_uuid: get_dm_uuid /dev/nvme0n1p1 uuid path is /sys/dev/block/259:1/dm/uuid
prepare_device: Journal /dev/nvme0n1p1 is a partition
get_dm_uuid: get_dm_uuid /dev/nvme0n1p1 uuid path is /sys/dev/block/259:1/dm/uuid
prepare_device: OSD will not be hot-swappable if journal is not the same device as the osd data
command: Running command: /sbin/blkid -o udev -p /dev/nvme0n1p1
prepare_device: Journal /dev/nvme0n1p1 was not prepared with ceph-disk. Symlinking directly.
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
set_data_partition: Creating osd partition on /dev/sda
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
ptype_tobe_for_name: name = data
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
create_partition: Creating data partition num 1 size 0 on /dev/sda
command_check_call: Running command: /sbin/sgdisk --largest-new=1 --change-name=1:ceph data --partition-guid=1:96b5036f-3aea-4711-b9e5-dbc32377b491 --typecode=1:89c57f98-2fe5-4dc0-89c1-f3ad0ceff2be --mbrtogpt -- /dev/sda
Creating new GPT entries.
The operation has completed successfully.
update_partition: Calling partprobe on created device /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /sbin/partprobe /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda1 uuid path is /sys/dev/block/8:1/dm/uuid
populate_data_path_device: Creating xfs fs on /dev/sda1
command_check_call: Running command: /sbin/mkfs -t xfs -f -i size=2048 -f -- /dev/sda1
meta-data=/dev/sda1              isize=2048   agcount=4, agsize=36593599 blks
         =                       sectsz=512   attr=2, projid32bit=0
data     =                       bsize=4096   blocks=146374395, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0
log      =internal log           bsize=4096   blocks=71471, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
mount: Mounting /dev/sda1 on /var/lib/ceph/tmp/mnt.5aK2XK with options noatime,inode64
command_check_call: Running command: /bin/mount -t xfs -o noatime,inode64 -- /dev/sda1 /var/lib/ceph/tmp/mnt.5aK2XK
populate_data_path: Preparing osd data dir /var/lib/ceph/tmp/mnt.5aK2XK
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.5aK2XK/ceph_fsid.7735.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.5aK2XK/fsid.7735.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.5aK2XK/magic.7735.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.5aK2XK/journal_uuid.7735.tmp
adjust_symlink: Creating symlink /var/lib/ceph/tmp/mnt.5aK2XK/journal -> /dev/nvme0n1p1
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.5aK2XK
unmount: Unmounting /var/lib/ceph/tmp/mnt.5aK2XK
command_check_call: Running command: /bin/umount -- /var/lib/ceph/tmp/mnt.5aK2XK
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command_check_call: Running command: /sbin/sgdisk --typecode=1:4fbd7e29-9d25-41b8-afd0-062c0ceff05d -- /dev/sda
The operation has completed successfully.
update_partition: Calling partprobe on prepared device /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /sbin/partprobe /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command_check_call: Running command: /sbin/udevadm trigger --action=add --sysname-match sda1
main_activate: path = /dev/sda
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sda
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4994, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4945, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3299, in main_activate
    reactivate=args.reactivate,
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3009, in mount_activate
    e,
ceph_disk.main.FilesystemTypeError: Cannot discover filesystem type: device /dev/sda: Line is truncated:
```
And then the docker container ends up in a restart loop that looks like this
```
2016-07-06T09:07:37Z vm04 confd[9234]: INFO Backend set to consul
2016-07-06T09:07:37Z vm04 confd[9234]: INFO Starting confd
2016-07-06T09:07:37Z vm04 confd[9234]: INFO Backend nodes set to vm01.se-ix.delta.prod:8500
Adding bootstrap keyrings
No bootstrapped OSDs found; trying ceph-disk
HEALTH_OK
ERROR- It looks like this device is an OSD, set OSD_FORCE_ZAP=1 to use this device anyway and zap its content
```
Problem appears to be that blkid is running against /dev/sda instead of /dev/sda1..
This is blocking me from deploying new dockerized ceph OSD's. I'm stuck here.. 😞 

I thought #313 would fix this for me, but it appears not to since i'm running latest tag-build-master-jewel-ubuntu-14.04

**Comment by leseb** [comment]
Oops, I forgot to push a new version of the branch, I just did, please wait for the build to finish :)

**Comment by leseb** [comment]
I'm closing this, feel free to re-open if the new version of the image doesn't solve this.

**Comment by Raboo** [comment]
Hi, the new image doesn't fix this issue..
```
2016-07-07T09:17:53Z vm04 confd[16319]: INFO Backend set to consul
2016-07-07T09:17:53Z vm04 confd[16319]: INFO Starting confd
2016-07-07T09:17:53Z vm04 confd[16319]: INFO Backend nodes set to vm01.se-ix.delta.prod:8500
2016-07-07T09:17:53Z vm04 confd[16319]: INFO Target config /etc/ceph/ceph.conf out of sync
2016-07-07T09:17:53Z vm04 confd[16319]: INFO Target config /etc/ceph/ceph.conf has been updated
Adding bootstrap keyrings
No bootstrapped OSDs found; trying ceph-disk
HEALTH_OK
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
command: Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=osd_journal_size
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
get_dm_uuid: get_dm_uuid /dev/nvme0n1p1 uuid path is /sys/dev/block/259:1/dm/uuid
prepare_device: Journal /dev/nvme0n1p1 is a partition
get_dm_uuid: get_dm_uuid /dev/nvme0n1p1 uuid path is /sys/dev/block/259:1/dm/uuid
prepare_device: OSD will not be hot-swappable if journal is not the same device as the osd data
command: Running command: /sbin/blkid -o udev -p /dev/nvme0n1p1
prepare_device: Journal /dev/nvme0n1p1 was not prepared with ceph-disk. Symlinking directly.
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
set_data_partition: Creating osd partition on /dev/sda
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
ptype_tobe_for_name: name = data
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
create_partition: Creating data partition num 1 size 0 on /dev/sda
command_check_call: Running command: /sbin/sgdisk --largest-new=1 --change-name=1:ceph data --partition-guid=1:1e1f0889-092e-42cf-ab9c-2082bc3edb3c --typecode=1:89c57f98-2fe5-4dc0-89c1-f3ad0ceff2be --mbrtogpt -- /dev/sda
Creating new GPT entries.
The operation has completed successfully.
update_partition: Calling partprobe on created device /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /sbin/partprobe /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda1 uuid path is /sys/dev/block/8:1/dm/uuid
populate_data_path_device: Creating xfs fs on /dev/sda1
command_check_call: Running command: /sbin/mkfs -t xfs -f -i size=2048 -f -- /dev/sda1
meta-data=/dev/sda1              isize=2048   agcount=4, agsize=36593599 blks
         =                       sectsz=512   attr=2, projid32bit=0
data     =                       bsize=4096   blocks=146374395, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0
log      =internal log           bsize=4096   blocks=71471, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
mount: Mounting /dev/sda1 on /var/lib/ceph/tmp/mnt.nKAxol with options noatime,inode64
command_check_call: Running command: /bin/mount -t xfs -o noatime,inode64 -- /dev/sda1 /var/lib/ceph/tmp/mnt.nKAxol
populate_data_path: Preparing osd data dir /var/lib/ceph/tmp/mnt.nKAxol
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.nKAxol/ceph_fsid.16376.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.nKAxol/fsid.16376.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.nKAxol/magic.16376.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.nKAxol/journal_uuid.16376.tmp
adjust_symlink: Creating symlink /var/lib/ceph/tmp/mnt.nKAxol/journal -> /dev/nvme0n1p1
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.nKAxol
unmount: Unmounting /var/lib/ceph/tmp/mnt.nKAxol
command_check_call: Running command: /bin/umount -- /var/lib/ceph/tmp/mnt.nKAxol
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command_check_call: Running command: /sbin/sgdisk --typecode=1:4fbd7e29-9d25-41b8-afd0-062c0ceff05d -- /dev/sda
The operation has completed successfully.
update_partition: Calling partprobe on prepared device /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /sbin/partprobe /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command_check_call: Running command: /sbin/udevadm trigger --action=add --sysname-match sda1
main_activate: path = /dev/sda
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sda
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4994, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 4945, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3299, in main_activate
    reactivate=args.reactivate,
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3009, in mount_activate
    e,
ceph_disk.main.FilesystemTypeError: Cannot discover filesystem type: device /dev/sda: Line is truncated:
```
Container restarts
```
2016-07-07T09:18:20Z vm04 confd[17994]: INFO Backend set to consul
2016-07-07T09:18:20Z vm04 confd[17994]: INFO Starting confd
2016-07-07T09:18:20Z vm04 confd[17994]: INFO Backend nodes set to vm01.se-ix.delta.prod:8500
Adding bootstrap keyrings
No bootstrapped OSDs found; trying ceph-disk
HEALTH_OK
ERROR- It looks like this device is an OSD, set OSD_FORCE_ZAP=1 to use this device anyway and zap its content
```

**Comment by leseb** [comment]
I can not reproduce this. I'm using prepare and activate steps.
Are you sure the device you are using (sda) is valid and not your system disk?

**Comment by Raboo** [comment]
Yes I'm sure, and it's not just /dev/sda
/dev/sda
/dev/sdb
/dev/sdc
/dev/sdd
/dev/sde
/dev/sdf
/dev/sdg
/dev/sdh

I just pasted logs for /dev/sda, but all are the same..
My plan is to use "Without OSD_TYPE" for the simple reason of making it more simple to automate.
Documentation says:
> disk is used if no bootstrapped OSD is found. OSD_FORCE_ZAP=1 must be set at this point.
activate is used if a bootstrapped OSD is found and OSD_DEVICE is also provided.
directory is used if a bootstrapped OSD is found and no OSD_DEVICE is provided.

So basically I have a chef recipe that for the first time starts the OSD's without a specified type and the disks will get bootstrapped since type disk will be used..
And whenever I need to restart, update or something the type activate will be used cause the disks are already bootstrapped.
This way I don't have to build advanced logic to prepare the disks, check if they are prepared, don't have build/start containers with first type prepare, then wait til they finish and remove the containers and then start new containers with type activate.. It just adds unnecessary complexity to the cookbook.

**Comment by leseb** [comment]
Somehow ceph-disk is running the blkid command on the raw device and not the partition, that's the problem. The line  `main_activate: path = /dev/sda` should use `/dev/sda1`.

I'm currently pushing a change to improve the discovery feature for osd scenarios.

**Comment by Raboo** [comment]
Ok, how can I help, should I file a bug/issue about ceph-disk in ceph/ceph?

**Comment by leseb** [comment]
@Raboo yes I think you should, try to open an issue on http://tracker.ceph.com/

**Comment by Raboo** [comment]
created a issue on ceph tracker
http://tracker.ceph.com/issues/16649

**Comment by leseb** [comment]
@Raboo cool, I'm closing this as this is not a ceph-docker issue ;)

**Comment by Raboo** [comment]
Question
I ran ceph-disk prepare manually on the host directly.
And it didn't really run /sbin/blkid against /dev/sda*. Pasted the output below.
It did run blkid against the journal partition. So this blkid against /dev/sda, is it perhaps the ceph-disk activate command that runs into this error?

https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L472

Perhaps it should use $(dev_part ${OSD_DEVICE} 1) instead of ${OSD_DEVICE} when activating?


```
# ceph-disk -v prepare /dev/sda /dev/nvme0n1p1
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
command: Running command: /usr/bin/ceph-osd --check-allows-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-wants-journal -i 0 --cluster ceph
command: Running command: /usr/bin/ceph-osd --check-needs-journal -i 0 --cluster ceph
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=osd_journal_size
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_type
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mkfs_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
get_dm_uuid: get_dm_uuid /dev/nvme0n1p1 uuid path is /sys/dev/block/259:1/dm/uuid
prepare_device: Journal /dev/nvme0n1p1 is a partition
get_dm_uuid: get_dm_uuid /dev/nvme0n1p1 uuid path is /sys/dev/block/259:1/dm/uuid
prepare_device: OSD will not be hot-swappable if journal is not the same device as the osd data
command: Running command: /sbin/blkid -o udev -p /dev/nvme0n1p1
prepare_device: Journal /dev/nvme0n1p1 was not prepared with ceph-disk. Symlinking directly.
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
set_data_partition: Creating osd partition on /dev/sda
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
ptype_tobe_for_name: name = data
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
create_partition: Creating data partition num 1 size 0 on /dev/sda
command_check_call: Running command: /sbin/sgdisk --largest-new=1 --change-name=1:ceph data --partition-guid=1:8781a4f5-bea3-4c73-897f-22707972783a --typecode=1:89c57f98-2fe5-4dc0-89c1-f3ad0ceff2be --mbrtogpt -- /dev/sda
Creating new GPT entries.
The operation has completed successfully.
update_partition: Calling partprobe on created device /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /sbin/partprobe /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
get_dm_uuid: get_dm_uuid /dev/sda1 uuid path is /sys/dev/block/8:1/dm/uuid
populate_data_path_device: Creating xfs fs on /dev/sda1
command_check_call: Running command: /sbin/mkfs -t xfs -f -i size=2048 -- /dev/sda1
meta-data=/dev/sda1              isize=2048   agcount=4, agsize=36593599 blks
         =                       sectsz=512   attr=2, projid32bit=0
data     =                       bsize=4096   blocks=146374395, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0
log      =internal log           bsize=4096   blocks=71471, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
mount: Mounting /dev/sda1 on /var/lib/ceph/tmp/mnt.aZm9q3 with options noatime,inode64
command_check_call: Running command: /bin/mount -t xfs -o noatime,inode64 -- /dev/sda1 /var/lib/ceph/tmp/mnt.aZm9q3
populate_data_path: Preparing osd data dir /var/lib/ceph/tmp/mnt.aZm9q3
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.aZm9q3/ceph_fsid.10706.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.aZm9q3/fsid.10706.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.aZm9q3/magic.10706.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.aZm9q3/journal_uuid.10706.tmp
adjust_symlink: Creating symlink /var/lib/ceph/tmp/mnt.aZm9q3/journal -> /dev/nvme0n1p1
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.aZm9q3
unmount: Unmounting /var/lib/ceph/tmp/mnt.aZm9q3
command_check_call: Running command: /bin/umount -- /var/lib/ceph/tmp/mnt.aZm9q3
get_dm_uuid: get_dm_uuid /dev/sda uuid path is /sys/dev/block/8:0/dm/uuid
command_check_call: Running command: /sbin/sgdisk --typecode=1:4fbd7e29-9d25-41b8-afd0-062c0ceff05d -- /dev/sda
The operation has completed successfully.
update_partition: Calling partprobe on prepared device /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command: Running command: /sbin/partprobe /dev/sda
command_check_call: Running command: /sbin/udevadm settle --timeout=600
command_check_call: Running command: /sbin/udevadm trigger --action=add --sysname-match sda1
```

**Comment by leseb** [comment]
@Raboo you're right this should be `$(dev_part ${OSD_DEVICE} 1) `.
Would you mind testing and then doing a PR?

Thanls!

**Comment by Raboo** [comment]
I did test, and it comes a lot further, but now fails cause it can't resolve the id..
My guess is that it fails in:
https://github.com/ceph/ceph-docker/blob/master/ceph-releases/jewel/ubuntu/14.04/daemon/entrypoint.sh#L610

```
start_daemon: Starting ceph osd.10...
command_check_call: Running command: /sbin/initctl emit --no-wait -- ceph-osd cluster=ceph id=10
df: '/var/lib/ceph/osd/ceph-/': No such file or directory
2016-07-11 13:08:40.836681 7ff972d6a700 -1 auth: unable to find a keyring on /var/lib/ceph/osd/ceph-/keyring: (2) No such file or directory
2016-07-11 13:08:40.836732 7ff972d6a700 -1 monclient(hunting): ERROR: missing keyring, cannot use cephx for authentication
2016-07-11 13:08:40.836746 7ff972d6a700  0 librados: osd. initialization error (2) No such file or directory
Error connecting to cluster: ObjectNotFound
```

**Comment by Raboo** [comment]
Ok, I've tested this pull request and it works for me :-)
https://github.com/ceph/ceph-docker/pull/333

**Comment by leseb** [comment]
Thanks!
